package main

import (
	"bufio"
	"fmt"
	"log"
	"net/http"
)

func main() {
	// get the book Adventures of Sherlock Holmes
	res, err := http.Get("http://www.gutenberg.org/cache/epub/1661/pg1661.txt")
	if err != nil {
		log.Fatal(err)
	}
	// scan the page
	scanner := bufio.NewScanner(res.Body)
	defer res.Body.Close()
	// set the split function for the scaning operation
	scanner.Split(bufio.ScanWords)
	// create map with a key of int
	// add a value of another map
	// with a key of string, which will be the word
	// add a value of int, which will be the number of times the word occurs
	buckets := make(map[int]map[string]int)
	// create slices to hold words
	for i := 0; i < 12; i++ {
		buckets[i] = make(map[string]int)
	}
	// loop over the words
	for scanner.Scan() {
		word := scanner.Text()
		n := HashBucket(word, 12)
		buckets[n][word]++
	}
	// Print words in a bucket
	for k, v := range buckets[6] {
		fmt.Println(v, "\t- ", k)
	}
}

// HashBucket - hash function
func HashBucket(word string, bucket int) int {
	var sum int
	for _, v := range word {
		sum += int(v)
	}
	return sum % bucket
}

/*
Run Result:
1       -  capacity
1       -  thus:
3       -  incisive
9       -  search
2       -  vacuous
1       -  War,
2       -  gross
18      -  single
1       -  made!"
1       -  interested--white,
1       -  furnished.
1       -  Under
1       -  oath.
1       -  sought
1       -  cargo.
2       -  question,"
3       -  lounged
1       -  smooth
4       -  "You'll
1       -  lunch,
1       -  country-houses.
1       -  vain,
1       -  CAN
12      -  send
2       -  chance."
4       -  ink,
1       -  obeyed.
1       -  Continent."
2       -  sleeve.
2       -  duties
2       -  pool,
1       -  jewel-case.
3       -  communication
1       -  passage.
2       -  Beryl
7       -  straight
1       -  detected
8       -  Coroner:
1       -  electronically,
4       -  "No;
1       -  tender
1       -  secret."
19      -  spoke
8       -  importance
2       -  die
3       -  "Some
10      -  immense
1       -  absorbed
1       -  undo
1       -  mining
1       -  impulsive
2       -  recommend
1       -  quest."
1       -  pallet
1       -  emaciation
3       -  Yours
21      -  lost
2       -  arm.
1       -  "Captain
5       -  building
1       -  sides.
1       -  descent,
1       -  gems.
1       -  deserted.
3       -  in!"
1       -  secretive,
1       -  aperture.
2       -  folded,
21      -  deep
3       -  rooms.
1       -  abrupt
1       -  perplexity
3       -  deductions
1       -  fain
54      -  My
1       -  avenue.
3       -  confidence
3       -  hansom,
1       -  beamed
3       -  to-night
1       -  Near
1       -  stand,
1       -  understanding
2       -  *****
1       -  fare
1       -  "Pshaw!
5       -  pocket,
1       -  hydrochloric
14      -  Frank
155     -  only
1       -  completely
12      -  start
1       -  relics
1       -  acetones,
14      -  figure
2       -  guardsmen
1       -  accomplice's
6       -  pipe,
1       -  disappoint?
4       -  event
1       -  history
15      -  again.
1       -  moss
1       -  best,
1       -  cleaver
1       -  brazen
1       -  assume
3       -  drive,
1       -  "Colonel
1       -  ends
2       -  blew
1       -  business,"
1       -  good-bye,
4       -  enough."
1       -  mankind
1       -  reasonable.
1       -  "Good-day,
1       -  free,
5       -  changed
1       -  planet.
1       -  contrary
4       -  imagine."
2       -  cardboard
1       -  Holland,
1       -  hinders.'
2       -  entrance.
1       -  studied,
1       -  prices,
1       -  fall;
1       -  scraped
76      -  make
1       -  coachman,
2       -  nostrils
1       -  surest
2       -  two,
1       -  bleeding,
1       -  go."
5       -  stranger
1       -  answer.
4       -  Farm
1       -  descend
1       -  vagabond
1       -  purse,'
1       -  synthesis
1       -  child?'
3       -  expected,
12      -  unless
1       -  Thoreau's
1       -  depositors.
4       -  sovereign
1       -  forbid
1       -  "'Keep
1       -  manageress
3       -  increased
1       -  self-poisoner
1       -  prosecuted
1       -  correspondent,
1       -  classes
2       -  weather.
49      -  morning
14      -  paid
1       -  more?
1       -  forces
1       -  Someone
3       -  good.'
1       -  sings.
40      -  lady
1       -  clients,
3       -  glasses,
3       -  here,"
1       -  vary
6       -  thousand
1       -  advantages,
6       -  results
6       -  down.
1       -  isolation
1       -  money,"
1       -  meadows.
1       -  Vere
1       -  walked.
1       -  write?
5       -  foul
3       -  regretted
3       -  Between
1       -  gainer
1       -  astonished
1       -  vacancies.'
1       -  presence--in
3       -  laughing;
1       -  encouraging
23      -  them,
2       -  rare
1       -  guilty,
1       -  suicide,
1       -  see--her
253     -  him
1       -  afternoon,"
2       -  gaping
1       -  Swain,
3       -  length
1       -  hungrily
1       -  e-mail)
1       -  regulating
1       -  fidelity
1       -  freedom
1       -  programme,
1       -  talk.
1       -  worn,
7       -  rain
2       -  back?"
1       -  "Suddenly,
2       -  sick
24      -  it?"
20      -  night,
15      -  didn't
6       -  knees
1       -  hear:
11      -  important
3       -  minutes.'
1       -  please."
1       -  proved.
1       -  brow,
17      -  seem
2       -  week's
1       -  nearest,
1       -  perplexing
1       -  conundrums."
2       -  quote
1       -  limped--he
2       -  improved
4       -  men.
1       -  copier
1       -  Hafiz
1       -  records,
2       -  absurdly
1       -  star,
4       -  "Precisely
3       -  Too
5       -  providing
4       -  correct,
460     -  upon
2       -  hang
1       -  ancient
1       -  miss?'
1       -  Hers
14      -  pay
2       -  will.
1       -  clenched
2       -  Station
3       -  paused
1       -  serious."
10      -  traces
1       -  damp,
1       -  novel.
1       -  woke
1       -  come,"
2       -  women,
1       -  1869,"
1       -  centuries
25      -  so,
4       -  promises
1       -  bag."
1       -  place--within
1       -  disputatious
1       -  wooded
1       -  crime,"
1       -  Cosmopolitan,"
1       -  unravelled
6       -  Adventure
1       -  catastrophe
1       -  verbatim
1       -  offhand
3       -  Scarlet,
1       -  quavering
1       -  arrows,
1       -  calculate
1       -  cabinet
2       -  Suburban
2       -  papers?
1       -  forestalling
6       -  Hunter
1       -  accepting
3       -  dark."
1       -  Capital
1       -  heaving
1       -  gambler,
1       -  mopping
1       -  "'Death,'
1       -  recently
2       -  Holder
1       -  hair?'
1       -  Aldershot,
2       -  indeed?"
8       -  play
2       -  conception
1       -  Foreign
2       -  June
1       -  troopers
1       -  king?"
2       -  none,"
8       -  swiftly
1       -  Farrington
2       -  else?"
1       -  boyish
1       -  terror."
1       -  lonelier
2       -  solemn
4       -  column
1       -  groom.
3       -  "because
1       -  harsh
1       -  idle
2       -  "Plain
2       -  endless
1       -  crudest
1       -  matter.'
1       -  shouted.
2       -  rope
1       -  indicating
2       -  refund.
4       -  moment.
1       -  Egria.
4       -  enough,
2       -  "Ah!"
10      -  Yet
1       -  "'A
1       -  then!"
1       -  boa
3       -  crackling
1       -  are,"
1       -  invaders.
1       -  clock.
1       -  jolted
1       -  secure--a
1       -  uncompromising
1       -  choked,
1       -  experience.
1       -  nothing?
1       -  satisfied.
6       -  rolled
4       -  young,
3       -  cry,
1       -  hoard,
1       -  conjunction
1       -  bridegroom,
1       -  uncouth
1       -  downloading,
1       -  To-day
1       -  'Where
2       -  brute
1       -  tone
7       -  thank
1       -  calf,
1       -  half-column
1       -  sharpened
1       -  insist
5       -  "From
2       -  gravity
6       -  this.
1       -  "You?
1       -  Since
257     -  little
2       -  summoned.
2       -  Wednesday.
1       -  of!
1       -  respectable,
1       -  fagged
1       -  draw."
2       -  performance
1       -  selection
1       -  breakfasts
1       -  resist
4       -  cold,
8       -  go,
1       -  successful.
1       -  askance
1       -  adviser
1       -  things?"
1       -  cheerful
1       -  clerks.
1       -  all-comprehensive
1       -  half-pay
1       -  character?"
3       -  certain,
1       -  father."
1       -  fainting.
2       -  metropolis,
1       -  choosing
2       -  equinoctial
1       -  blowing,
58      -  eyes
1       -  packet.
1       -  funny.
1       -  Attica,
1       -  outcry
1       -  protruding,
1       -  feathers,
1       -  persevering
2       -  hoarse
1       -  selfish
1       -  son's,
5       -  possession
1       -  broadened.
1       -  fish
4       -  imagine,
1       -  Bordeaux,
7       -  Christmas
140     -  other
4       -  appearance.
1       -  autumn
6       -  life.
1       -  pie
1       -  escapade
1       -  version
1       -  crates
1       -  baby
1       -  Shipping
1       -  pencils
1       -  observer--excellent
1       -  rustic
3       -  advice.
1       -  assailants;
4       -  approach
1       -  "This,
3       -  pew.
12      -  deduce
25      -  "We
1       -  queer
1       -  brim
5       -  interesting.
2       -  details,
1       -  Scott!
1       -  tooth
1       -  identify.
1       -  innocence,
3       -  deed
1       -  nose?"
1       -  into,
4       -  signature
38      -  When
1       -  smile,
3       -  week.
1       -  Rotterdam."
1       -  time--a
1       -  slab,
1       -  drive."
1       -  crusted
17      -  close
16      -  there.
1       -  landowner,
1       -  be;
2       -  secret,
2       -  "Eh?
2       -  introduction
1       -  crawled
5       -  web
2       -  added
2       -  confessed
1       -  confronted
1       -  Cedars
1       -  secretary
10      -  merely
23      -  one,
4       -  borne
1       -  haggard,
1       -  aunt's
1       -  out-of-the-way
1       -  portly,
3       -  paper.
2       -  throat,
1       -  intend
5       -  friend.
1       -  bath-sponge.
1       -  WILSON"
4       -  chemical
1       -  sorely,
1       -  calling,
1       -  turned,
16      -  love
2       -  summons
4       -  visible
1       -  elbowed
1       -  Boswell.
1       -  gift
1       -  singularly
1       -  free."
1       -  pardon.
1       -  goals
5       -  "this
1       -  rather."
4       -  roof
3       -  "'Tell
2       -  baggy
1       -  "Watson,
2       -  uneasiness
1       -  cheerless,
3       -  rather,
1       -  limits,
1       -  beasts
2       -  locket
5       -  dark,
1       -  "Good-evening.
1       -  fleeting
2       -  501(c)(3)
4       -  arrested
1       -  market.
1       -  "'Lord
1       -  NOTICE
1       -  "American
1       -  successes?"
4       -  loose
1       -  manor-house
2       -  course!
1       -  shouts
1       -  nickel
1       -  "Without,
8       -  explained
1       -  white-counterpaned
1       -  mistaken.
1       -  uttering
2       -  mention
4       -  attention,
1       -  Principal
1       -  intensified
1       -  concert
1       -  planned
1       -  horsey
5       -  "Now
6       -  matter?"
1       -  expiring
1       -  disfigured
1       -  his,"
1       -  architects,
23      -  sister
1       -  22nd,
1       -  excursion.
1       -  demurely;
1       -  revellers.
1       -  customer
1       -  rapidity
1       -  was;
7       -  exactly
2       -  "'Not
1       -  coster's
1       -  excluded
1       -  representations
195     -  our
7       -  hands."
1       -  Club
1       -  records."
4       -  swear
1       -  savagely.
1       -  does;
8       -  endeavoured
1       -  trophy
1       -  conjectured,
1       -  rate.
2       -  director.
2       -  linen
1       -  followed.
1       -  believe,"
2       -  Menendez
2       -  asleep,
1       -  $5,000)
1       -  persons,
20      -  London
1       -  word,"
1       -  wears
1       -  swish
1       -  pockets?"
1       -  glass,
12      -  voice
3       -  existence.
15      -  lamp
6       -  date
3       -  composed
1       -  shadow,
4       -  Information
1       -  office.
1       -  district
1       -  jaw,
1       -  mates,
1       -  Think
2       -  sandwiched
5       -  obliged
2       -  noticed,
2       -  frost
2       -  Sutherland
1       -  intimacy,
4       -  lane.
17      -  charge
1       -  discourage
1       -  unhealthy
1       -  decide
1       -  10s.
1       -  Bradshaw.
8       -  "Why,
2       -  proprietor
2       -  "Surely
1       -  trifle."
1       -  '87
6       -  America
1       -  acquired
1       -  Bring
6       -  country.
1       -  rushes
1       -  "There,
1       -  acquirement
1       -  cart
2       -  suited
10      -  boy
1       -  suicide."
1       -  receded.
1       -  tallow-stains
1       -  'Perhaps
1       -  obese,
1       -  'Omne
5       -  Hatherley,
2       -  address,
1       -  shutters,
42      -  behind
4       -  committed
1       -  conclusions,"
1       -  geniality
1       -  attention."
6       -  notice
3       -  miles,
1       -  ruby
1       -  despairing
6       -  secrecy
1       -  peace
1       -  imbecility!"
2       -  effort,
1       -  girl."
2       -  pity,
2       -  beer
1       -  blandly,
1       -  chairs,
1       -  boomed
1       -  steps;
1       -  performer
1       -  streets,
1       -  dwell.
1       -  civilisation,
1       -  throat."
1       -  assures
1       -  custom,'
1       -  Cross
1       -  harmony,
2       -  tragedy.
1       -  granting
1       -  skirmishes,
1       -  enemies,
5       -  big
1       -  quest,
1       -  look?"
6       -  rush
2       -  shoulder
2       -  fortunes,
1       -  Trepoff
1       -  courtesy
1       -  public-house.
4       -  letter.
1       -  Eustace
1       -  Mission
1       -  thus.
1       -  discretion.
43      -  head
2       -  numerous
4       -  well-known
3       -  avert
1       -  stepfather."
1       -  horse?"
1       -  originator
14      -  Boscombe
9       -  out.
1       -  ground-floor,
3       -  proceed
3       -  acting
1       -  symptoms.
3       -  cloak
3       -  Pope's
2       -  sketch
1       -  then--a
2       -  men's
1       -  however,"
1       -  staples.
3       -  situation.
1       -  scene."
21      -  house.
1       -  shelves
5       -  hurry
7       -  God
1       -  elementary,
2       -  Among
1       -  variable,
2       -  thoughtful
1       -  benevolent
1       -  ha!
1       -  ex-Confederate
1       -  Doctor;
2       -  crushed
3       -  understand,"
7       -  estate,
1       -  Hood,
2       -  "Nothing?"
1       -  terror,
2       -  extending
12      -  myself.
1       -  pounds.'
3       -  Lascar,
1       -  shop,
1       -  Baker?"
1       -  Something
1       -  depicted
9       -  stretched
1       -  peep
2       -  Doran's
1       -  Chesterfield,
2       -  advanced
165     -  can
15      -  observed
8       -  incident
3       -  "Last
1       -  Embankment
1       -  bell-rope,
2       -  Englishman,
1       -  CONTRACT
1       -  "Read
3       -  routine
6       -  seated
1       -  gone.'
1       -  Australia."
1       -  hope.
2       -  moment's
1       -  adapt
2       -  bonnet,
3       -  complying
1       -  well-groomed
1       -  'Letters,
2       -  drifted
2       -  stately
1       -  Assizes
1       -  French,
1       -  see?"
1       -  "she
1       -  plenty.
2       -  title
9       -  she.
1       -  dawn
7       -  missing
8       -  girl,
2       -  warmly.
2       -  her;
1       -  buying
15      -  glance
1       -  "Has
1       -  Moran?"
2       -  clamped
1       -  (801)
4       -  clothes,
4       -  sun
1       -  died,
2       -  opinion.
2       -  details."
1       -  Cornwall
4       -  flush
1       -  fetch
1       -  interrupted
2       -  ways.
1       -  thirty-seven
1       -  trifle,
1       -  Peterson's
1       -  lock?"
51      -  got
5       -  careful
1       -  assaulted
1       -  "Six
1       -  excited,
3       -  downstairs,
1       -  antics
1       -  do,'
1       -  partially
1       -  Finns
1       -  heap
1       -  ulsters
1       -  want,
16      -  dropped
1       -  managing
1       -  chains
1       -  innocence."
1       -  Gutenberg"),
1       -  Fairbank
1       -  sin
10      -  so."
1       -  innocent."
1       -  ragged
1       -  await
2       -  final
1       -  well-lit
1       -  training.
1       -  alas!
1       -  defence
1       -  scheming
2       -  perpetual
1       -  re-marriage.
1       -  items
1       -  burly
1       -  doings:
9       -  remark
1       -  deceased,
1       -  downward
1       -  scratching
1       -  pocket."
1       -  trouser.
2       -  Bradstreet.
1       -  "Warm!
6       -  ***
2       -  annoyed
1       -  directed.
1       -  maybe,
1       -  Garden.'
1       -  gbnewby@pglaf.org
3       -  walks
1       -  Bristol?
2       -  war
1       -  peaked
1       -  shabbily
1       -  luncheon.
4       -  conjecture
1       -  science,
1       -  dipped
1       -  garment
2       -  DAMAGES
1       -  feeling,
2       -  patted
1       -  conduct.
1       -  affairs,"
1       -  dreamy
1       -  métier,
1       -  murderer
5       -  fingers
7       -  prisoner
1       -  curse
1       -  cell.
2       -  on?"
1       -  fulfil
1       -  landlord.
2       -  "Ha!"
24      -  appeared
1       -  youth?"
1       -  vague.
1       -  quarrel.
2       -  60
1       -  concluding
3       -  past.
1       -  though;
1       -  severed
1       -  rubber
1       -  bearing.
1       -  Bank.
2       -  hat?"
3       -  beef
1       -  Balmoral
1       -  co-operation.
1       -  sounded,
1       -  employment
35      -  woman
10      -  returning
1       -  denying
1       -  intruding.
1       -  duty,
2       -  village.
3       -  highroad,
1       -  untamed
1       -  clue?"
2       -  "Well
1       -  enwrapped
2       -  three.
1       -  landing-places
1       -  over,"
2       -  Adler.
4       -  mistake
8       -  fifty
1       -  lids.
2       -  B
1       -  purchase;
1       -  stronger.
1       -  laughed,
5       -  gun
2       -  map
1       -  explanations
3       -  there's
5       -  palm
2       -  envelope,
1       -  Elise!'
1       -  identification
1       -  barbaric
1       -  vivid
6       -  "'That
1       -  chase,"
1       -  suitor
2       -  rifled
1       -  century,
2       -  servants,
29      -  five
50      -  day
3       -  neighbours,
2       -  travel
1       -  arguments,
1       -  blaze."
7       -  stepfather,
1       -  wives
1       -  comfort
1       -  supplied
1       -  Montana,
1       -  modification,
1       -  enjoyed
1       -  evidence;
1       -  tragic,
2       -  this:
1       -  squat
2       -  engine
1       -  temples
414     -  me
1       -  admiration.
1       -  whoa!"
1       -  "Good-morning,
1       -  ﻿Project
10      -  questioning
1       -  prosperous
9       -  English
8       -  them."
2       -  shoes
1       -  reverse.
1       -  4d.
3       -  Winchester.
7       -  reasoning
1       -  disentangled
4       -  please,
4       -  firm,
1       -  precious,
1       -  Cassel-Felstein,
6       -  wedding
4       -  it.'
1       -  "Tired-looking
1       -  education.
1       -  virtues
1       -  apply,
1       -  "life
1       -  shilling
1       -  removed,
1       -  http://pglaf.org/donate
4       -  check
1       -  Men?'
1       -  spoils
2       -  beard
1       -  heavily,
1       -  1883.
1       -  sake,"
1       -  scene,
6       -  hands,
2       -  me!'
3       -  stones.
1       -  happening
3       -  remaining
4       -  homely
1       -  found--never,
1       -  Jane,
1       -  later.
3       -  pale,
4       -  knock
3       -  breath
1       -  accustomed.
1       -  nominal
24      -  sir,
3       -  night."
2       -  entries
1       -  accomplice.
2       -  came,
1       -  umbrella,"
1       -  Robert,
7       -  scandal
1       -  Armour
1       -  Same
1       -  incredulity.
1       -  closed,
1       -  cruelty's
12      -  "'You
2       -  Road
1       -  rouse
3       -  concerning
1       -  inches,
1       -  minute,
13      -  father,
*/
